
import { Category } from '../types';

export const japaneseWords: Category[] = [
  {
    name: 'Saudações e Frases',
    icon: '👋',
    words: [
      { japanese: 'おはようございます', romaji: 'Ohayō gozaimasu', portuguese: 'Bom dia (formal)', english: 'Good morning (formal)' },
      { japanese: 'おはよう', romaji: 'Ohayō', portuguese: 'Bom dia (informal)', english: 'Good morning (informal)' },
      { japanese: 'こんにちは', romaji: 'Konnichiwa', portuguese: 'Olá / Boa tarde', english: 'Hello / Good afternoon' },
      { japanese: 'こんばんは', romaji: 'Konbanwa', portuguese: 'Boa noite (ao chegar)', english: 'Good evening' },
      { japanese: 'おやすみなさい', romaji: 'Oyasuminasai', portuguese: 'Boa noite (ao se despedir)', english: 'Good night' },
      { japanese: 'さようなら', romaji: 'Sayōnara', portuguese: 'Adeus', english: 'Goodbye' },
      { japanese: 'じゃあね', romaji: 'Jā ne', portuguese: 'Até mais / Tchau', english: 'See you / Bye' },
      { japanese: 'また明日', romaji: 'Mata ashita', portuguese: 'Até amanhã', english: 'See you tomorrow' },
      { japanese: 'ありがとう', romaji: 'Arigatō', portuguese: 'Obrigado(a)', english: 'Thank you' },
      { japanese: 'ありがとうございます', romaji: 'Arigatō gozaimasu', portuguese: 'Muito obrigado(a) (formal)', english: 'Thank you very much (formal)' },
      { japanese: 'どういたしまして', romaji: 'Dō itashimashite', portuguese: 'De nada', english: 'You\'re welcome' },
      { japanese: 'すみません', romaji: 'Sumimasen', portuguese: 'Com licença / Desculpe', english: 'Excuse me / Sorry' },
      { japanese: 'ごめんなさい', romaji: 'Gomen nasai', portuguese: 'Me desculpe', english: 'I\'m sorry' },
      { japanese: 'はい', romaji: 'Hai', portuguese: 'Sim', english: 'Yes' },
      { japanese: 'いいえ', romaji: 'Iie', portuguese: 'Não', english: 'No' },
      { japanese: 'お願いします', romaji: 'Onegai shimasu', portuguese: 'Por favor', english: 'Please' },
      { japanese: 'どうぞ', romaji: 'Dōzo', portuguese: 'Por favor (oferecendo algo)', english: 'Please (offering something)' },
      { japanese: 'いただきます', romaji: 'Itadakimasu', portuguese: 'Obrigado pela comida (antes de comer)', english: 'Thanks for the food (before eating)' },
      { japanese: 'ごちそうさまでした', romaji: 'Gochisōsama deshita', portuguese: 'Obrigado pela comida (depois de comer)', english: 'Thanks for the food (after eating)' },
      { japanese: '元気ですか', romaji: 'Genki desu ka?', portuguese: 'Como você está?', english: 'How are you?' },
      { japanese: '元気です', romaji: 'Genki desu', portuguese: 'Estou bem', english: 'I am fine' },
      { japanese: 'はじめまして', romaji: 'Hajimemashite', portuguese: 'Prazer em conhecê-lo', english: 'Nice to meet you' },
      { japanese: 'どうぞよろしく', romaji: 'Dōzo yoroshiku', portuguese: 'Prazer em conhecê-lo (continuação)', english: 'Pleased to meet you' },
      { japanese: 'いってきます', romaji: 'Ittekimasu', portuguese: 'Estou saindo (e volto)', english: 'I\'m leaving (and will be back)' },
      { japanese: 'いってらっしゃい', romaji: 'Itterasshai', portuguese: 'Vá com cuidado (resposta a ittekimasu)', english: 'Take care (response to ittekimasu)' },
      { japanese: 'ただいま', romaji: 'Tadaima', portuguese: 'Cheguei / Estou de volta', english: 'I\'m home / I\'m back' },
      { japanese: 'おかえりなさい', romaji: 'Okaerinasai', portuguese: 'Bem-vindo(a) de volta', english: 'Welcome back' },
      { japanese: 'もしもし', romaji: 'Moshi moshi', portuguese: 'Alô (ao telefone)', english: 'Hello (on the phone)' },
    ],
    sentences: [
        { japanese: 'これはペンです。', romaji: 'Kore wa pen desu.', portuguese: 'Isto é uma caneta.', english: 'This is a pen.' },
        { japanese: '田中さんは日本人です。', romaji: 'Tanaka-san wa nihonjin desu.', portuguese: 'O Sr. Tanaka é japonês.', english: 'Mr. Tanaka is Japanese.' },
        { japanese: '私はブラジル人です。', romaji: 'Watashi wa burajirujin desu.', portuguese: 'Eu sou brasileiro.', english: 'I am Brazilian.' },
        { japanese: '駅はどこですか。', romaji: 'Eki wa doko desu ka?', portuguese: 'Onde fica a estação?', english: 'Where is the station?' },
        { japanese: 'これをください。', romaji: 'Kore o kudasai.', portuguese: 'Me dê isto, por favor.', english: 'This one, please.' },
    ]
  },
  {
    name: 'Números',
    icon: '🔢',
    words: [
      { japanese: '一', romaji: 'Ichi', portuguese: 'Um', english: 'One' },
      { japanese: '二', romaji: 'Ni', portuguese: 'Dois', english: 'Two' },
      { japanese: '三', romaji: 'San', portuguese: 'Três', english: 'Three' },
      { japanese: '四', romaji: 'Shi / Yon', portuguese: 'Quatro', english: 'Four' },
      { japanese: '五', romaji: 'Go', portuguese: 'Cinco', english: 'Five' },
      { japanese: '六', romaji: 'Roku', portuguese: 'Seis', english: 'Six' },
      { japanese: '七', romaji: 'Shichi / Nana', portuguese: 'Sete', english: 'Seven' },
      { japanese: '八', romaji: 'Hachi', portuguese: 'Oito', english: 'Eight' },
      { japanese: '九', romaji: 'Kyū / Ku', portuguese: 'Nove', english: 'Nine' },
      { japanese: '十', romaji: 'Jū', portuguese: 'Dez', english: 'Ten' },
      { japanese: '十一', romaji: 'Jū ichi', portuguese: 'Onze', english: 'Eleven' },
      { japanese: '十二', romaji: 'Jū ni', portuguese: 'Doze', english: 'Twelve' },
      { japanese: '二十', romaji: 'Nijū', portuguese: 'Vinte', english: 'Twenty' },
      { japanese: '三十', romaji: 'Sanjū', portuguese: 'Trinta', english: 'Thirty' },
      { japanese: '四十', romaji: 'Yonjū', portuguese: 'Quarenta', english: 'Forty' },
      { japanese: '五十', romaji: 'Gojū', portuguese: 'Cinquenta', english: 'Fifty' },
      { japanese: '百', romaji: 'Hyaku', portuguese: 'Cem', english: 'One hundred' },
      { japanese: '千', romaji: 'Sen', portuguese: 'Mil', english: 'One thousand' },
      { japanese: '万', romaji: 'Man', portuguese: 'Dez mil', english: 'Ten thousand' },
      { japanese: '〇 / ゼロ', romaji: 'Zero / Rei', portuguese: 'Zero', english: 'Zero' },
    ],
  },
  {
    name: 'Pessoas e Família',
    icon: '👨‍👩‍👧‍👦',
    words: [
        { japanese: '人', romaji: 'Hito', portuguese: 'Pessoa', english: 'Person' },
        { japanese: '男', romaji: 'Otoko', portuguese: 'Homem', english: 'Man' },
        { japanese: '女', romaji: 'Onna', portuguese: 'Mulher', english: 'Woman' },
        { japanese: '子供', romaji: 'Kodomo', portuguese: 'Criança', english: 'Child' },
        { japanese: '友達', romaji: 'Tomodachi', portuguese: 'Amigo', english: 'Friend' },
        { japanese: '家族', romaji: 'Kazoku', portuguese: 'Família', english: 'Family' },
        { japanese: '私', romaji: 'Watashi', portuguese: 'Eu', english: 'I / Me' },
        { japanese: 'あなた', romaji: 'Anata', portuguese: 'Você', english: 'You' },
        { japanese: '彼', romaji: 'Kare', portuguese: 'Ele', english: 'He / Him' },
        { japanese: '彼女', romaji: 'Kanojo', portuguese: 'Ela', english: 'She / Her' },
        { japanese: '父', romaji: 'Chichi', portuguese: 'Meu pai', english: 'My father' },
        { japanese: 'お父さん', romaji: 'Otōsan', portuguese: 'Pai (de outra pessoa / formal)', english: 'Father (someone else\'s / formal)' },
        { japanese: '母', romaji: 'Haha', portuguese: 'Minha mãe', english: 'My mother' },
        { japanese: 'お母さん', romaji: 'Okāsan', portuguese: 'Mãe (de outra pessoa / formal)', english: 'Mother (someone else\'s / formal)' },
        { japanese: '兄', romaji: 'Ani', portuguese: 'Meu irmão mais velho', english: 'My older brother' },
        { japanese: 'お兄さん', romaji: 'Onīsan', portuguese: 'Irmão mais velho (de outra pessoa / formal)', english: 'Older brother (someone else\'s / formal)' },
        { japanese: '姉', romaji: 'Ane', portuguese: 'Minha irmã mais velha', english: 'My older sister' },
        { japanese: 'お姉さん', romaji: 'Onēsan', portuguese: 'Irmã mais velha (de outra pessoa / formal)', english: 'Older sister (someone else\'s / formal)' },
        { japanese: '弟', romaji: 'Otōto', portuguese: 'Meu irmão mais novo', english: 'My younger brother' },
        { japanese: '妹', romaji: 'Imōto', portuguese: 'Minha irmã mais nova', english: 'My younger sister' },
        { japanese: '祖父', romaji: 'Sofu', portuguese: 'Meu avô', english: 'My grandfather' },
        { japanese: 'おじいさん', romaji: 'Ojīsan', portuguese: 'Avô', english: 'Grandfather' },
        { japanese: '祖母', romaji: 'Sobo', portuguese: 'Minha avó', english: 'My grandmother' },
        { japanese: 'おばあさん', romaji: 'Obāsan', portuguese: 'Avó', english: 'Grandmother' },
        { japanese: '夫', romaji: 'Otto', portuguese: 'Meu marido', english: 'My husband' },
        { japanese: '妻', romaji: 'Tsuma', portuguese: 'Minha esposa', english: 'My wife' },
        { japanese: '赤ちゃん', romaji: 'Akachan', portuguese: 'Bebê', english: 'Baby' },
    ]
  },
  {
    name: 'Comida e Bebida',
    icon: '🍔',
    words: [
      { japanese: '食べ物', romaji: 'Tabemono', portuguese: 'Comida', english: 'Food' },
      { japanese: '飲み物', romaji: 'Nomimono', portuguese: 'Bebida', english: 'Drink' },
      { japanese: 'ご飯', romaji: 'Gohan', portuguese: 'Arroz cozido / Refeição', english: 'Cooked rice / Meal' },
      { japanese: 'パン', romaji: 'Pan', portuguese: 'Pão', english: 'Bread' },
      { japanese: '肉', romaji: 'Niku', portuguese: 'Carne', english: 'Meat' },
      { japanese: '魚', romaji: 'Sakana', portuguese: 'Peixe', english: 'Fish' },
      { japanese: '野菜', romaji: 'Yasai', portuguese: 'Vegetais / Legumes', english: 'Vegetables' },
      { japanese: '果物', romaji: 'Kudamono', portuguese: 'Fruta', english: 'Fruit' },
      { japanese: '水', romaji: 'Mizu', portuguese: 'Água', english: 'Water' },
      { japanese: 'お茶', romaji: 'Ocha', portuguese: 'Chá verde', english: 'Green tea' },
      { japanese: '紅茶', romaji: 'Kōcha', portuguese: 'Chá preto', english: 'Black tea' },
      { japanese: '牛乳', romaji: 'Gyūnyū', portuguese: 'Leite', english: 'Milk' },
      { japanese: 'ジュース', romaji: 'Jūsu', portuguese: 'Suco', english: 'Juice' },
      { japanese: 'コーヒー', romaji: 'Kōhī', portuguese: 'Café', english: 'Coffee' },
      { japanese: 'ビール', romaji: 'Bīru', portuguese: 'Cerveja', english: 'Beer' },
      { japanese: 'お酒', romaji: 'Osake', portuguese: 'Bebida alcoólica / Saquê', english: 'Alcoholic drink / Sake' },
      { japanese: '卵', romaji: 'Tamago', portuguese: 'Ovo', english: 'Egg' },
      { japanese: '砂糖', romaji: 'Satō', portuguese: 'Açúcar', english: 'Sugar' },
      { japanese: '塩', romaji: 'Shio', portuguese: 'Sal', english: 'Salt' },
      { japanese: '醤油', romaji: 'Shōyu', portuguese: 'Molho de soja', english: 'Soy sauce' },
      { japanese: '朝ご飯', romaji: 'Asagohan', portuguese: 'Café da manhã', english: 'Breakfast' },
      { japanese: '昼ご飯', romaji: 'Hirugohan', portuguese: 'Almoço', english: 'Lunch' },
      { japanese: '晩ご飯', romaji: 'Bangohan', portuguese: 'Jantar', english: 'Dinner' },
      { japanese: 'りんご', romaji: 'Ringo', portuguese: 'Maçã', english: 'Apple' },
      { japanese: 'みかん', romaji: 'Mikan', portuguese: 'Tangerina', english: 'Mandarin orange' },
      { japanese: 'バナナ', romaji: 'Banana', portuguese: 'Banana', english: 'Banana' },
      { japanese: 'いちご', romaji: 'Ichigo', portuguese: 'Morango', english: 'Strawberry' },
    ],
  },
    {
    name: 'Transporte',
    icon: '✈️',
    words: [
        { japanese: '電車', romaji: 'Densha', portuguese: 'Trem', english: 'Train' },
        { japanese: '車', romaji: 'Kuruma', portuguese: 'Carro', english: 'Car' },
        { japanese: 'バス', romaji: 'Basu', portuguese: 'Ônibus', english: 'Bus' },
        { japanese: 'タクシー', romaji: 'Takushī', portuguese: 'Táxi', english: 'Taxi' },
        { japanese: '自転車', romaji: 'Jitensha', portuguese: 'Bicicleta', english: 'Bicycle' },
        { japanese: '飛行機', romaji: 'Hikōki', portuguese: 'Avião', english: 'Airplane' },
        { japanese: '船', romaji: 'Fune', portuguese: 'Navio / Barco', english: 'Ship / Boat' },
        { japanese: '地下鉄', romaji: 'Chikatetsu', portuguese: 'Metrô', english: 'Subway' },
        { japanese: '新幹線', romaji: 'Shinkansen', portuguese: 'Trem-bala', english: 'Bullet train' },
        { japanese: '歩いて', romaji: 'Aruite', portuguese: 'A pé', english: 'On foot' },
    ]
  },
  {
    name: 'Animais',
    icon: '🐶',
    words: [
      { japanese: '動物', romaji: 'Dōbutsu', portuguese: 'Animal', english: 'Animal' },
      { japanese: '犬', romaji: 'Inu', portuguese: 'Cachorro', english: 'Dog' },
      { japanese: '猫', romaji: 'Neko', portuguese: 'Gato', english: 'Cat' },
      { japanese: '鳥', romaji: 'Tori', portuguese: 'Pássaro', english: 'Bird' },
      { japanese: '兎', romaji: 'Usagi', portuguese: 'Coelho', english: 'Rabbit' },
      { japanese: '鼠', romaji: 'Nezumi', portuguese: 'Rato', english: 'Mouse / Rat' },
      { japanese: '馬', romaji: 'Uma', portuguese: 'Cavalo', english: 'Horse' },
      { japanese: '牛', romaji: 'Ushi', portuguese: 'Vaca / Boi', english: 'Cow / Ox' },
      { japanese: '豚', romaji: 'Buta', portuguese: 'Porco', english: 'Pig' },
      { japanese: '羊', romaji: 'Hitsuji', portuguese: 'Ovelha', english: 'Sheep' },
      { japanese: '猿', romaji: 'Saru', portuguese: 'Macaco', english: 'Monkey' },
      { japanese: '鶏', romaji: 'Niwatori', portuguese: 'Galinha / Frango', english: 'Chicken' },
      { japanese: '蛇', romaji: 'Hebi', portuguese: 'Cobra', english: 'Snake' },
      { japanese: '熊', romaji: 'Kuma', portuguese: 'Urso', english: 'Bear' },
      { japanese: '虎', romaji: 'Tora', portuguese: 'Tigre', english: 'Tiger' },
      { japanese: '龍', romaji: 'Ryū / Tatsu', portuguese: 'Dragão', english: 'Dragon' },
      { japanese: '金魚', romaji: 'Kingyo', portuguese: 'Peixinho dourado', english: 'Goldfish' },
      { japanese: '虫', romaji: 'Mushi', portuguese: 'Inseto', english: 'Insect' },
    ],
  },
  {
    name: 'Corpo',
    icon: '💪',
    words: [
      { japanese: '体', romaji: 'Karada', portuguese: 'Corpo', english: 'Body' },
      { japanese: '頭', romaji: 'Atama', portuguese: 'Cabeça', english: 'Head' },
      { japanese: '髪', romaji: 'Kami', portuguese: 'Cabelo', english: 'Hair' },
      { japanese: '顔', romaji: 'Kao', portuguese: 'Rosto', english: 'Face' },
      { japanese: '目', romaji: 'Me', portuguese: 'Olho', english: 'Eye' },
      { japanese: '耳', romaji: 'Mimi', portuguese: 'Orelha', english: 'Ear' },
      { japanese: '鼻', romaji: 'Hana', portuguese: 'Nariz', english: 'Nose' },
      { japanese: '口', romaji: 'Kuchi', portuguese: 'Boca', english: 'Mouth' },
      { japanese: '歯', romaji: 'Ha', portuguese: 'Dente', english: 'Tooth' },
      { japanese: '首', romaji: 'Kubi', portuguese: 'Pescoço', english: 'Neck' },
      { japanese: '肩', romaji: 'Kata', portuguese: 'Ombro', english: 'Shoulder' },
      { japanese: '腕', romaji: 'Ude', portuguese: 'Braço', english: 'Arm' },
      { japanese: '手', romaji: 'Te', portuguese: 'Mão', english: 'Hand' },
      { japanese: '指', romaji: 'Yubi', portuguese: 'Dedo', english: 'Finger' },
      { japanese: '背中', romaji: 'Senaka', portuguese: 'Costas', english: 'Back' },
      { japanese: 'お腹', romaji: 'Onaka', portuguese: 'Barriga / Estômago', english: 'Stomach / Abdomen' },
      { japanese: '足', romaji: 'Ashi', portuguese: 'Pé / Perna', english: 'Foot / Leg' },
      { japanese: '膝', romaji: 'Hiza', portuguese: 'Joelho', english: 'Knee' },
      { japanese: '心', romaji: 'Kokoro', portuguese: 'Coração / Mente', english: 'Heart / Mind' },
    ],
  },
  {
    name: 'Lugares e Direções',
    icon: '🗺️',
    words: [
      { japanese: '場所', romaji: 'Basho', portuguese: 'Lugar', english: 'Place' },
      { japanese: '家', romaji: 'Ie / Uchi', portuguese: 'Casa', english: 'House' },
      { japanese: '学校', romaji: 'Gakkō', portuguese: 'Escola', english: 'School' },
      { japanese: '大学', romaji: 'Daigaku', portuguese: 'Universidade', english: 'University' },
      { japanese: '駅', romaji: 'Eki', portuguese: 'Estação de trem', english: 'Train station' },
      { japanese: '空港', romaji: 'Kūkō', portuguese: 'Aeroporto', english: 'Airport' },
      { japanese: '病院', romaji: 'Byōin', portuguese: 'Hospital', english: 'Hospital' },
      { japanese: '銀行', romaji: 'Ginkō', portuguese: 'Banco', english: 'Bank' },
      { japanese: '郵便局', romaji: 'Yūbinkyoku', portuguese: 'Correio', english: 'Post office' },
      { japanese: '図書館', romaji: 'Toshokan', portuguese: 'Biblioteca', english: 'Library' },
      { japanese: '店', romaji: 'Mise', portuguese: 'Loja', english: 'Shop / Store' },
      { japanese: 'レストラン', romaji: 'Resutoran', portuguese: 'Restaurante', english: 'Restaurant' },
      { japanese: 'ホテル', romaji: 'Hoteru', portuguese: 'Hotel', english: 'Hotel' },
      { japanese: '公園', romaji: 'Kōen', portuguese: 'Parque', english: 'Park' },
      { japanese: 'トイレ', romaji: 'Toire', portuguese: 'Banheiro', english: 'Toilet / Restroom' },
      { japanese: '右', romaji: 'Migi', portuguese: 'Direita', english: 'Right' },
      { japanese: '左', romaji: 'Hidari', portuguese: 'Esquerda', english: 'Left' },
      { japanese: '上', romaji: 'Ue', portuguese: 'Cima / Sobre', english: 'Up / Above' },
      { japanese: '下', romaji: 'Shita', portuguese: 'Baixo / Sob', english: 'Down / Below' },
      { japanese: '前', romaji: 'Mae', portuguese: 'Frente', english: 'Front' },
      { japanese: '後ろ', romaji: 'Ushiro', portuguese: 'Atrás', english: 'Behind' },
      { japanese: '中', romaji: 'Naka', portuguese: 'Dentro', english: 'Inside' },
      { japanese: '外', romaji: 'Soto', portuguese: 'Fora', english: 'Outside' },
      { japanese: '隣', romaji: 'Tonari', portuguese: 'Ao lado', english: 'Next to' },
      { japanese: '近く', romaji: 'Chikaku', portuguese: 'Perto', english: 'Near' },
      { japanese: '遠く', romaji: 'Tōku', portuguese: 'Longe', english: 'Far' },
    ],
  },
  {
    name: 'Tempo e Calendário',
    icon: '📅',
    words: [
      { japanese: '時間', romaji: 'Jikan', portuguese: 'Tempo / Hora', english: 'Time / Hour' },
      { japanese: '今日', romaji: 'Kyō', portuguese: 'Hoje', english: 'Today' },
      { japanese: '昨日', romaji: 'Kinō', portuguese: 'Ontem', english: 'Yesterday' },
      { japanese: '明日', romaji: 'Ashita', portuguese: 'Amanhã', english: 'Tomorrow' },
      { japanese: '朝', romaji: 'Asa', portuguese: 'Manhã', english: 'Morning' },
      { japanese: '昼', romaji: 'Hiru', portuguese: 'Meio-dia / Tarde', english: 'Noon / Afternoon' },
      { japanese: '夕方', romaji: 'Yūgata', portuguese: 'Fim de tarde', english: 'Evening' },
      { japanese: '夜', romaji: 'Yoru', portuguese: 'Noite', english: 'Night' },
      { japanese: '今', romaji: 'Ima', portuguese: 'Agora', english: 'Now' },
      { japanese: '後で', romaji: 'Ato de', portuguese: 'Depois', english: 'Later' },
      { japanese: '毎日', romaji: 'Mainichi', portuguese: 'Todos os dias', english: 'Every day' },
      { japanese: '毎週', romaji: 'Maishū', portuguese: 'Toda semana', english: 'Every week' },
      { japanese: '毎月', romaji: 'Maitsuki', portuguese: 'Todo mês', english: 'Every month' },
      { japanese: '毎年', romaji: 'Mainen / Maitoshi', portuguese: 'Todo ano', english: 'Every year' },
      { japanese: '週', romaji: 'Shū', portuguese: 'Semana', english: 'Week' },
      { japanese: '月曜日', romaji: 'Getsuyōbi', portuguese: 'Segunda-feira', english: 'Monday' },
      { japanese: '火曜日', romaji: 'Kayōbi', portuguese: 'Terça-feira', english: 'Tuesday' },
      { japanese: '水曜日', romaji: 'Suiyōbi', portuguese: 'Quarta-feira', english: 'Wednesday' },
      { japanese: '木曜日', romaji: 'Mokuyōbi', portuguese: 'Quinta-feira', english: 'Thursday' },
      { japanese: '金曜日', romaji: 'Kinyōbi', portuguese: 'Sexta-feira', english: 'Friday' },
      { japanese: '土曜日', romaji: 'Doyōbi', portuguese: 'Sábado', english: 'Saturday' },
      { japanese: '日曜日', romaji: 'Nichiyōbi', portuguese: 'Domingo', english: 'Sunday' },
      { japanese: '月', romaji: 'Tsuki / Gatsu', portuguese: 'Mês / Lua', english: 'Month / Moon' },
      { japanese: '年', romaji: 'Toshi / Nen', portuguese: 'Ano', english: 'Year' },
      { japanese: '春', romaji: 'Haru', portuguese: 'Primavera', english: 'Spring' },
      { japanese: '夏', romaji: 'Natsu', portuguese: 'Verão', english: 'Summer' },
      { japanese: '秋', romaji: 'Aki', portuguese: 'Outono', english: 'Autumn / Fall' },
      { japanese: '冬', romaji: 'Fuyu', portuguese: 'Inverno', english: 'Winter' },
    ],
  },
  {
    name: 'Natureza',
    icon: '🌳',
    words: [
      { japanese: '自然', romaji: 'Shizen', portuguese: 'Natureza', english: 'Nature' },
      { japanese: '山', romaji: 'Yama', portuguese: 'Montanha', english: 'Mountain' },
      { japanese: '川', romaji: 'Kawa', portuguese: 'Rio', english: 'River' },
      { japanese: '海', romaji: 'Umi', portuguese: 'Mar', english: 'Sea / Ocean' },
      { japanese: '空', romaji: 'Sora', portuguese: 'Céu', english: 'Sky' },
      { japanese: '天気', romaji: 'Tenki', portuguese: 'Tempo (clima)', english: 'Weather' },
      { japanese: '晴れ', romaji: 'Hare', portuguese: 'Ensolarado', english: 'Sunny' },
      { japanese: '曇り', romaji: 'Kumori', portuguese: 'Nublado', english: 'Cloudy' },
      { japanese: '雨', romaji: 'Ame', portuguese: 'Chuva', english: 'Rain' },
      { japanese: '雪', romaji: 'Yuki', portuguese: 'Neve', english: 'Snow' },
      { japanese: '風', romaji: 'Kaze', portuguese: 'Vento', english: 'Wind' },
      { japanese: '雷', romaji: 'Kaminari', portuguese: 'Trovão', english: 'Thunder' },
      { japanese: '太陽', romaji: 'Taiyō', portuguese: 'Sol', english: 'Sun' },
      { japanese: '月', romaji: 'Tsuki', portuguese: 'Lua', english: 'Moon' },
      { japanese: '星', romaji: 'Hoshi', portuguese: 'Estrela', english: 'Star' },
      { japanese: '木', romaji: 'Ki', portuguese: 'Árvore', english: 'Tree' },
      { japanese: '花', romaji: 'Hana', portuguese: 'Flor', english: 'Flower' },
      { japanese: '石', romaji: 'Ishi', portuguese: 'Pedra', english: 'Stone' },
      { japanese: '火', romaji: 'Hi', portuguese: 'Fogo', english: 'Fire' },
    ],
  },
  {
    name: 'Objetos e Coisas',
    icon: '✏️',
    words: [
      { japanese: '物', romaji: 'Mono', portuguese: 'Coisa / Objeto', english: 'Thing / Object' },
      { japanese: 'これ', romaji: 'Kore', portuguese: 'Isto (perto de quem fala)', english: 'This (near speaker)' },
      { japanese: 'それ', romaji: 'Sore', portuguese: 'Isso (perto de quem ouve)', english: 'That (near listener)' },
      { japanese: 'あれ', romaji: 'Are', portuguese: 'Aquilo (longe de ambos)', english: 'That (far from both)' },
      { japanese: '本', romaji: 'Hon', portuguese: 'Livro', english: 'Book' },
      { japanese: '辞書', romaji: 'Jisho', portuguese: 'Dicionário', english: 'Dictionary' },
      { japanese: '雑誌', romaji: 'Zasshi', portuguese: 'Revista', english: 'Magazine' },
      { japanese: '新聞', romaji: 'Shinbun', portuguese: 'Jornal', english: 'Newspaper' },
      { japanese: '机', romaji: 'Tsukue', portuguese: 'Mesa / Escrivaninha', english: 'Desk / Table' },
      { japanese: '椅子', romaji: 'Isu', portuguese: 'Cadeira', english: 'Chair' },
      { japanese: '鉛筆', romaji: 'Enpitsu', portuguese: 'Lápis', english: 'Pencil' },
      { japanese: 'ペン', romaji: 'Pen', portuguese: 'Caneta', english: 'Pen' },
      { japanese: '紙', romaji: 'Kami', portuguese: 'Papel', english: 'Paper' },
      { japanese: '鞄', romaji: 'Kaban', portuguese: 'Bolsa / Mala', english: 'Bag' },
      { japanese: '靴', romaji: 'Kutsu', portuguese: 'Sapatos', english: 'Shoes' },
      { japanese: '時計', romaji: 'Tokei', portuguese: 'Relógio', english: 'Clock / Watch' },
      { japanese: '傘', romaji: 'Kasa', portuguese: 'Guarda-chuva', english: 'Umbrella' },
      { japanese: '電話', romaji: 'Denwa', portuguese: 'Telefone', english: 'Telephone' },
      { japanese: '鍵', romaji: 'Kagi', portuguese: 'Chave', english: 'Key' },
      { japanese: 'お金', romaji: 'Okane', portuguese: 'Dinheiro', english: 'Money' },
      { japanese: '写真', romaji: 'Shashin', portuguese: 'Fotografia', english: 'Photograph' },
      { japanese: 'テレビ', romaji: 'Terebi', portuguese: 'Televisão', english: 'Television' },
      { japanese: 'パソコン', romaji: 'Pasokon', portuguese: 'Computador pessoal', english: 'Personal computer' },
      { japanese: '窓', romaji: 'Mado', portuguese: 'Janela', english: 'Window' },
      { japanese: 'ドア', romaji: 'Doa', portuguese: 'Porta', english: 'Door' },
    ],
  },
  {
    name: 'Verbos Comuns',
    icon: '🏃',
    words: [
      { japanese: 'する', romaji: 'Suru', portuguese: 'Fazer', english: 'To do' },
      { japanese: '来る', romaji: 'Kuru', portuguese: 'Vir', english: 'To come' },
      { japanese: '行く', romaji: 'Iku', portuguese: 'Ir', english: 'To go' },
      { japanese: 'いる', romaji: 'Iru', portuguese: 'Existir / Estar (seres vivos)', english: 'To be / exist (animate)' },
      { japanese: 'ある', romaji: 'Aru', portuguese: 'Existir / Ter (objetos)', english: 'To be / exist (inanimate)' },
      { japanese: '食べる', romaji: 'Taberu', portuguese: 'Comer', english: 'To eat' },
      { japanese: '飲む', romaji: 'Nomu', portuguese: 'Beber', english: 'To drink' },
      { japanese: '見る', romaji: 'Miru', portuguese: 'Ver / Assistir', english: 'To see / watch' },
      { japanese: '聞く', romaji: 'Kiku', portuguese: 'Ouvir / Perguntar', english: 'To listen / ask' },
      { japanese: '読む', romaji: 'Yomu', portuguese: 'Ler', english: 'To read' },
      { japanese: '書く', romaji: 'Kaku', portuguese: 'Escrever', english: 'To write' },
      { japanese: '話す', romaji: 'Hanasu', portuguese: 'Falar', english: 'To speak' },
      { japanese: '言う', romaji: 'Iu', portuguese: 'Dizer', english: 'To say' },
      { japanese: '買う', romaji: 'Kau', portuguese: 'Comprar', english: 'To buy' },
      { japanese: '売る', romaji: 'Uru', portuguese: 'Vender', english: 'To sell' },
      { japanese: '待つ', romaji: 'Matsu', portuguese: 'Esperar', english: 'To wait' },
      { japanese: '会う', romaji: 'Au', portuguese: 'Encontrar', english: 'To meet' },
      { japanese: '寝る', romaji: 'Neru', portuguese: 'Dormir', english: 'To sleep' },
      { japanese: '起きる', romaji: 'Okiru', portuguese: 'Acordar / Levantar', english: 'To wake up / get up' },
      { japanese: '帰る', romaji: 'Kaeru', portuguese: 'Voltar (para casa)', english: 'To return (home)' },
      { japanese: '働く', romaji: 'Hataraku', portuguese: 'Trabalhar', english: 'To work' },
      { japanese: '勉強する', romaji: 'Benkyō suru', portuguese: 'Estudar', english: 'To study' },
      { japanese: '分かる', romaji: 'Wakaru', portuguese: 'Entender', english: 'To understand' },
      { japanese: '知る', romaji: 'Shiru', portuguese: 'Saber / Conhecer', english: 'To know' },
      { japanese: '遊ぶ', romaji: 'Asobu', portuguese: 'Brincar / Divertir-se', english: 'To play / have fun' },
      { japanese: '泳ぐ', romaji: 'Oyogu', portuguese: 'Nadar', english: 'To swim' },
      { japanese: '死ぬ', romaji: 'Shinu', portuguese: 'Morrer', english: 'To die' },
      { japanese: '使う', romaji: 'Tsukau', portuguese: 'Usar', english: 'To use' },
      { japanese: '作る', romaji: 'Tsukuru', portuguese: 'Fazer / Criar / Produzir', english: 'To make / create / produce' },
      { japanese: '入る', romaji: 'Hairu', portuguese: 'Entrar', english: 'To enter' },
      { japanese: '出る', romaji: 'Deru', portuguese: 'Sair', english: 'To leave / go out' },
    ],
  },
  {
    name: 'Adjetivos Comuns',
    icon: '🎨',
    words: [
      { japanese: '良い', romaji: 'Ii / Yoi', portuguese: 'Bom', english: 'Good' },
      { japanese: '悪い', romaji: 'Warui', portuguese: 'Mau / Ruim', english: 'Bad' },
      { japanese: '大きい', romaji: 'Ōkii', portuguese: 'Grande', english: 'Big' },
      { japanese: '小さい', romaji: 'Chiisai', portuguese: 'Pequeno', english: 'Small' },
      { japanese: '高い', romaji: 'Takai', portuguese: 'Alto / Caro', english: 'High / Expensive' },
      { japanese: '安い', romaji: 'Yasui', portuguese: 'Barato', english: 'Cheap' },
      { japanese: '低い', romaji: 'Hikui', portuguese: 'Baixo', english: 'Low' },
      { japanese: '新しい', romaji: 'Atarashii', portuguese: 'Novo', english: 'New' },
      { japanese: '古い', romaji: 'Furui', portuguese: 'Velho', english: 'Old' },
      { japanese: '熱い', romaji: 'Atsui', portuguese: 'Quente (coisas, clima)', english: 'Hot (things, weather)' },
      { japanese: '寒い', romaji: 'Samui', portuguese: 'Frio (clima)', english: 'Cold (weather)' },
      { japanese: '冷たい', romaji: 'Tsumetai', portuguese: 'Frio (coisas)', english: 'Cold (to the touch)' },
      { japanese: '難しい', romaji: 'Muzukashii', portuguese: 'Difícil', english: 'Difficult' },
      { japanese: '易しい', romaji: 'Yasashii', portuguese: 'Fácil', english: 'Easy' },
      { japanese: '面白い', romaji: 'Omoshiroi', portuguese: 'Interessante / Engraçado', english: 'Interesting / Funny' },
      { japanese: 'つまらない', romaji: 'Tsumaranai', portuguese: 'Entediante', english: 'Boring' },
      { japanese: '美味しい', romaji: 'Oishii', portuguese: 'Delicioso', english: 'Delicious' },
      { japanese: 'まずい', romaji: 'Mazui', portuguese: 'Ruim (sabor)', english: 'Bad-tasting' },
      { japanese: '楽しい', romaji: 'Tanoshii', portuguese: 'Divertido', english: 'Fun' },
      { japanese: '忙しい', romaji: 'Isogashii', portuguese: 'Ocupado', english: 'Busy' },
      { japanese: '嬉しい', romaji: 'Ureshii', portuguese: 'Feliz / Contente', english: 'Happy / Glad' },
      { japanese: '悲しい', romaji: 'Kanashii', portuguese: 'Triste', english: 'Sad' },
      { japanese: '近い', romaji: 'Chikai', portuguese: 'Perto', english: 'Near' },
      { japanese: '遠い', romaji: 'Tōi', portuguese: 'Longe', english: 'Far' },
      { japanese: '速い', romaji: 'Hayai', portuguese: 'Rápido / Cedo', english: 'Fast / Early' },
      { japanese: '遅い', romaji: 'Osoi', portuguese: 'Lento / Tarde', english: 'Slow / Late' },
      { japanese: '多い', romaji: 'Ōi', portuguese: 'Muitos', english: 'Many / Much' },
      { japanese: '少ない', romaji: 'Sukunai', portuguese: 'Poucos', english: 'Few / Little' },
      { japanese: '甘い', romaji: 'Amai', portuguese: 'Doce', english: 'Sweet' },
      { japanese: '辛い', romaji: 'Karai', portuguese: 'Apimentado', english: 'Spicy' },
      { japanese: '可愛い', romaji: 'Kawaii', portuguese: 'Fofo / Bonitinho', english: 'Cute' },
      { japanese: 'きれい', romaji: 'Kirei (na)', portuguese: 'Bonito / Limpo', english: 'Beautiful / Clean' },
      { japanese: '元気', romaji: 'Genki (na)', portuguese: 'Saudável / Enérgico', english: 'Healthy / Energetic' },
      { japanese: '静か', romaji: 'Shizuka (na)', portuguese: 'Quieto / Calmo', english: 'Quiet / Calm' },
      { japanese: '好き', romaji: 'Suki (na)', portuguese: 'Gostar', english: 'Likeable' },
      { japanese: '嫌い', romaji: 'Kirai (na)', portuguese: 'Odiar / Não gostar', english: 'Dislikeable' },
    ],
  },
    {
    name: 'Cores',
    icon: '🌈',
    words: [
        { japanese: '色', romaji: 'Iro', portuguese: 'Cor', english: 'Color' },
        { japanese: '赤 / 赤い', romaji: 'Aka / Akai', portuguese: 'Vermelho', english: 'Red' },
        { japanese: '青 / 青い', romaji: 'Ao / Aoi', portuguese: 'Azul', english: 'Blue' },
        { japanese: '黒 / 黒い', romaji: 'Kuro / Kuroi', portuguese: 'Preto', english: 'Black' },
        { japanese: '白 / 白い', romaji: 'Shiro / Shiroi', portuguese: 'Branco', english: 'White' },
        { japanese: '黄 / 黄色い', romaji: 'Ki / Kiiroi', portuguese: 'Amarelo', english: 'Yellow' },
        { japanese: '緑', romaji: 'Midori', portuguese: 'Verde', english: 'Green' },
        { japanese: '紫', romaji: 'Murasaki', portuguese: 'Roxo', english: 'Purple' },
        { japanese: 'ピンク', romaji: 'Pinku', portuguese: 'Rosa', english: 'Pink' },
        { japanese: 'オレンジ', romaji: 'Orenji', portuguese: 'Laranja', english: 'Orange' },
        { japanese: '茶色', romaji: 'Chairo', portuguese: 'Marrom', english: 'Brown' },
        { japanese: '灰色', romaji: 'Haiiro', portuguese: 'Cinza', english: 'Gray' },
        { japanese: '金色', romaji: 'Kin\'iro', portuguese: 'Dourado', english: 'Gold' },
        { japanese: '銀色', romaji: 'Gin\'iro', portuguese: 'Prateado', english: 'Silver' },
    ]
  },
  {
      name: 'Advérbios',
      icon: '✨',
      words: [
          { japanese: 'とても', romaji: 'Totemo', portuguese: 'Muito', english: 'Very' },
          { japanese: '少し', romaji: 'Sukoshi', portuguese: 'Um pouco', english: 'A little' },
          { japanese: 'たくさん', romaji: 'Takusan', portuguese: 'Muito (quantidade)', english: 'A lot / Many' },
          { japanese: 'いつも', romaji: 'Itsumo', portuguese: 'Sempre', english: 'Always' },
          { japanese: '時々', romaji: 'Tokidoki', portuguese: 'Às vezes', english: 'Sometimes' },
          { japanese: 'よく', romaji: 'Yoku', portuguese: 'Frequentemente / Bem', english: 'Often / Well' },
          { japanese: 'もう', romaji: 'Mō', portuguese: 'Já / Mais', english: 'Already / Anymore' },
          { japanese: 'まだ', romaji: 'Mada', portuguese: 'Ainda', english: 'Still / Yet' },
          { japanese: '一緒に', romaji: 'Issho ni', portuguese: 'Juntos', english: 'Together' },
          { japanese: 'ゆっくり', romaji: 'Yukkuri', portuguese: 'Devagar', english: 'Slowly' },
      ]
  }
];
